"""Agent catalog models. An entry is a preset describing an agent type
the orchestrator can launch: harness runtime, optional default LiteLLM
model, and display metadata. The image lives on agent_versions;
``current_version`` points at the version sandboxes boot with.

Admins register entries via ``POST /api/agents``. Session creation
takes an ``agent_id`` and resolves the agent through this catalog for
the harness, the current version's image, and (when the caller omits
one) the model. Callers can still pass ``model`` explicitly to override
the agent's default.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import ClassVar, Self

from mothership_client.client_models.aggregation import AggregationInput
from mothership_client.client_models.api_output_model import ApiOutputModel
from mothership_client.client_models.common import DatetimeFilter, KeywordFilter, StringFilter
from mothership_client.client_models.pagination import PaginationInput
from mothership_client.models.harness import HarnessType, TransportMode
from mothership_client.validators import strip_or_reject_blank
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class AgentParameter(BaseModel):
    """A runtime config value a sandbox container needs (auth token,
    API base URL, etc.). The orchestrator injects each resolved value
    as an env var named ``key`` into every container in the sandbox
    stack (init, harness, lifeline) so mcporter / harness configs /
    lifeline sync code can pick it up the same way regardless of which
    runtime needs it.

    ``default`` gives session-create a prefilled value. ``None`` means
    the caller must supply one — the session-create endpoint errors
    if any parameter without a default is missing. ``secret`` is a
    UI/log hint: masked in the admin UI, omitted from create/update
    responses. It does not today map to k8s Secret resources (env
    vars go inline); that's a follow-up when real secret-store
    integration is needed.
    """

    model_config = ConfigDict(extra="forbid")

    key: str = Field(min_length=1, pattern=r"^[A-Z_][A-Z0-9_]*$")
    label: str = Field(min_length=1)
    description: str = ""
    default: str | None = None
    secret: bool = False


class AgentCatalogEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # Generated surrogate id (``agent_XXXXX``).
    agent_id: str
    # Human, caller-facing identifier, unique within the owning org.
    slug: str
    # Owning org. Surfaced for the platform-admin
    # cross-org views; org-scoped reads already know the org from the path.
    org_id: str | None = None
    name: str
    description: str = ""
    harness: HarnessType = HarnessType.OPENCLAW
    transport: TransportMode = TransportMode.RELAY
    # version_id of the agent_versions row sandboxes should boot with.
    # None until the agent has a version (every create makes one).
    current_version: str | None = None
    # Display-only: the human ``version`` label for ``current_version``,
    # resolved on read paths (get/search). None on write responses.
    current_version_label: str | None = None
    default_model: str | None = None
    is_active: bool = True
    parameters: list[AgentParameter] = Field(default_factory=list)
    thread_deeplink_template: str | None = None
    # Messaging connectors this agent supports (discord, slack, …). Drives
    # plugin install + which secret params are required. The per-connector
    # config (guild allowlist, streaming, …) is supplied per sandbox, not here.
    enabled_channels: list[str] = Field(default_factory=list)
    created_at: datetime | None = None
    updated_at: datetime | None = None


def _validate_unique_parameter_keys(parameters: list[AgentParameter]) -> list[AgentParameter]:
    keys = [p.key for p in parameters]
    if len(keys) != len(set(keys)):
        dups = sorted({k for k in keys if keys.count(k) > 1})
        raise ValueError(f"duplicate parameter keys: {dups}")
    return parameters


class AgentVersionSpec(BaseModel):
    """One version to mint when creating an agent: a free-form label plus
    the Docker image it pins."""

    model_config = ConfigDict(extra="forbid")

    version: str = Field(min_length=1)
    image: str = Field(min_length=1)
    date_built: datetime | None = None
    enabled: bool = True


class CreateAgentInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # Human, caller-facing identifier, unique within the owning org. Admins
    # pick this — kebab-case like ``shippy-main`` or ``shippy-internal``. The
    # surrogate ``agent_id`` (``agent_XXXXX``) is generated by the data access;
    # callers never supply it.
    slug: str = Field(min_length=1, pattern=r"^[a-z0-9][a-z0-9-]*$")
    name: str = Field(min_length=1)
    description: str = ""
    harness: HarnessType = HarnessType.OPENCLAW
    # Transport fronting the agent: relay (native gateway) or bus (mothership
    # channel). bus is currently only implemented for the openclaw harness.
    transport: TransportMode = TransportMode.RELAY
    # Single-version shorthand: provide ``image`` (+ optional ``version``
    # label, defaulting to the image string) OR the ``versions`` list below,
    # not both. The image must be resolvable from the orchestrator's pull
    # context. After validation ``versions`` is always populated.
    image: str | None = Field(default=None, min_length=1)
    version: str | None = Field(default=None, min_length=1)
    date_built: datetime | None = None
    # Mint several versions at once. ``default_version`` (a label) becomes
    # the agent's current_version; it defaults to the first entry. Labels
    # must be unique and the default must be enabled.
    versions: list[AgentVersionSpec] | None = None
    default_version: str | None = Field(default=None, min_length=1)
    # LiteLLM model session-create falls back to when a caller omits
    # ``model``. Optional — agents that don't set one force callers
    # to supply ``model`` explicitly. Empty string is rejected so a
    # blank field in the admin UI doesn't masquerade as a default.
    default_model: str | None = Field(default=None, min_length=1)
    is_active: bool = True
    parameters: list[AgentParameter] = Field(default_factory=list)
    thread_deeplink_template: str | None = None
    enabled_channels: list[str] = Field(default_factory=list)

    @field_validator("parameters")
    @classmethod
    def _unique_keys(cls, v: list[AgentParameter]) -> list[AgentParameter]:
        return _validate_unique_parameter_keys(v)

    @field_validator("default_model", mode="before")
    @classmethod
    def _strip_default_model(cls, v: str | None) -> str | None:
        return strip_or_reject_blank(v)

    @model_validator(mode="after")
    def _normalize_versions(self) -> Self:
        """Collapse the ``image`` shorthand into ``versions`` and resolve
        ``default_version`` so the data access always sees a non-empty list
        and a default label."""
        if self.versions is None:
            if not self.image:
                raise ValueError("provide either 'image' or 'versions'")
            self.versions = [AgentVersionSpec(version=self.version or self.image, image=self.image, date_built=self.date_built)]
        else:
            if self.image:
                raise ValueError("provide either 'image' or 'versions', not both")
            if not self.versions:
                raise ValueError("'versions' must be non-empty")
        labels = [v.version for v in self.versions]
        if len(labels) != len(set(labels)):
            raise ValueError("duplicate version labels")
        default = self.default_version or self.versions[0].version
        if default not in labels:
            raise ValueError(f"default_version {default!r} is not one of the provided versions")
        if not next(v for v in self.versions if v.version == default).enabled:
            raise ValueError("default_version must be enabled")
        self.default_version = default
        return self


class UpdateAgentInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # Path parameter; excluded from the patch payload serialized to the DB.
    agent_id: str

    name: str | None = None
    description: str | None = None
    harness: HarnessType | None = None
    transport: TransportMode | None = None
    # Repoint the agent at a different existing version. The version must
    # belong to this agent and be enabled (validated in the data access).
    current_version: str | None = Field(default=None, min_length=1)
    # Sentinel: omit the key to leave the column unchanged, or pass
    # ``null`` to explicitly clear the agent's default. Empty strings
    # are rejected so a blank UI field doesn't masquerade as a default.
    default_model: str | None = Field(default=None, min_length=1)
    is_active: bool | None = None
    parameters: list[AgentParameter] | None = None
    thread_deeplink_template: str | None = None
    # Sentinel: omit to leave enabled_channels unchanged; pass [] to clear.
    enabled_channels: list[str] | None = None

    @field_validator("parameters")
    @classmethod
    def _unique_keys(cls, v: list[AgentParameter] | None) -> list[AgentParameter] | None:
        return None if v is None else _validate_unique_parameter_keys(v)

    @field_validator("default_model", mode="before")
    @classmethod
    def _strip_default_model(cls, v: str | None) -> str | None:
        return strip_or_reject_blank(v)


class AgentCatalogSortBy(StrEnum):
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    NAME = "name"


class AgentCatalogFilterFields(BaseModel, extra="forbid"):
    agent_id: KeywordFilter[str] | None = None
    slug: KeywordFilter[str] | None = None
    # Cross-org filter for the platform-admin views; org-scoped reads AND their
    # own org onto this server-side.
    org_id: KeywordFilter[str] | None = None
    # StringFilter (not KeywordFilter) so the admin UI's name box can do
    # substring search; the eq/inc shape is a subset.
    name: StringFilter | None = None
    harness: KeywordFilter[HarnessType] | None = None
    transport: KeywordFilter[TransportMode] | None = None
    is_active: bool | None = None
    created_at: DatetimeFilter | None = None
    updated_at: DatetimeFilter | None = None


class SearchAgentCatalogInput(AgentCatalogFilterFields, PaginationInput[AgentCatalogSortBy]):
    sort_by: AgentCatalogSortBy = AgentCatalogSortBy.CREATED_AT


class AggregateAgentCatalogInput(AgentCatalogFilterFields, AggregationInput):
    _excluded_aggregatable_fields: ClassVar[set[str]] = {"agent_id"}


SearchAgentCatalogOutput = ApiOutputModel[AgentCatalogEntry]
AgentCatalogOutput = ApiOutputModel[AgentCatalogEntry]
